(load "Desktop/IA/IA1617projv04/scripts/datastructures.lisp")

(defun make-list-track (track)
    (let ((lst (list ))
          (sublst (list ))
          (size (track-size track))
          (lines 0)
          (columns 0))
        (setq lines (nth 0 size))
        (setq columns (nth 1 size))
        (dotimes (n lines)
            (setq sublst (list ))
            (dotimes (m columns)
                  (setq sublst (cons most-positive-fixnum sublst))
                  )
            (setq lst (cons sublst lst))
            )
          lst
        )
    )
